//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAtelierMVVM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalariesDBEntities : DbContext
    {
        public SalariesDBEntities()
            : base("name=SalariesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DemandeCreation> DemandeCreations { get; set; }
        public virtual DbSet<Demande> Demandes { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<ServiceAdmin> ServiceAdmins { get; set; }
    }
}
