// <auto-generated />
namespace ClientAtelierMVVM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init55 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init55));
        
        string IMigrationMetadata.Id
        {
            get { return "202110210921033_init55"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
